#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

pattern="^(feat|fix|docs|style|refactor|test|chore|perf) : .+"

if ! [[ $commit_msg =~ $pattern ]]; then
    echo "[에러]: 커밋 메세지 포맷이 맞지 않습니다!"
    echo "커밋 접두어를 다음과 같이 설정해 주세요"
    echo "feat :, fix :, docs :, style :, refactor :, test :, chore :, perf :"
    echo "Example : 'feat: Add new feature'"
    exit 1
fi
